#!/usr/bin/zsh
export FOREGROUND=a8a19f
export BACKGROUND=1b1918

export BLACK=1b1918
export RED=f22c40
export GREEN=5ab738
export YELLOW=d5911a
export BLUE=407ee7
export MAGENTA=6666ea
export CYAN=00ad9c
export WHITE=a8a19f

export BOLD_BLACK=766e6b
export BOLD_RED=f22c40
export BOLD_GREEN=5ab738
export BOLD_YELLOW=d5911a
export BOLD_BLUE=407ee7
export BOLD_MAGENTA=6666ea
export BOLD_CYAN=00ad9c
export BOLD_WHITE=f1efee

export CURSOR_COLOR=$YELLOW

