#!/usr/bin/zsh
export FOREGROUND=ab9bab
export BACKGROUND=1b181b

export BLACK=1b181b
export RED=ca402b
export GREEN=379a37
export YELLOW=bb8a35
export BLUE=516aec
export MAGENTA=7b59c0
export CYAN=159393
export WHITE=ab9bab

export BOLD_BLACK=776977
export BOLD_RED=ca402b
export BOLD_GREEN=379a37
export BOLD_YELLOW=bb8a35
export BOLD_BLUE=516aec
export BOLD_MAGENTA=7b59c0
export BOLD_CYAN=159393
export BOLD_WHITE=f7f3f7

export CURSOR_COLOR=$YELLOW

