#!/usr/bin/zsh
export FOREGROUND=e8e0b4
export BACKGROUND=1c354d

export BLACK=132334
export RED=ed5665
export GREEN=56ed73
export YELLOW=e8e0b4
export BLUE=8399e3
export MAGENTA=ed56b6
export CYAN=56ede7
export WHITE=e8e5d2

export BOLD_BLACK=080e15
export BOLD_RED=ed8d96
export BOLD_GREEN=67ff84
export BOLD_YELLOW=cab645
export BOLD_BLUE=9fa9c9
export BOLD_MAGENTA=ed96cd
export BOLD_CYAN=82c6c4
export BOLD_WHITE=f6f5ec

export CURSOR_COLOR=$YELLOW

