#!/usr/bin/zsh
export FOREGROUND=b7b8b9
export BACKGROUND=0c0d0e

export BLACK=0c0d0e
export RED=e31a1c
export GREEN=31a354
export YELLOW=dca060
export BLUE=3182bd
export MAGENTA=756bb1
export CYAN=80b1d3
export WHITE=b7b8b9

export BOLD_BLACK=737475
export BOLD_RED=e31a1c
export BOLD_GREEN=31a354
export BOLD_YELLOW=dca060
export BOLD_BLUE=3182bd
export BOLD_MAGENTA=756bb1
export BOLD_CYAN=80b1d3
export BOLD_WHITE=fcfdfe

export CURSOR_COLOR=$YELLOW

