#!/usr/bin/zsh
export FOREGROUND=3e3e3e
export BACKGROUND=f0e9dc

export BLACK=3e3e3e
export RED=966575
export GREEN=659675
export YELLOW=968665
export BLUE=657596
export MAGENTA=756596
export CYAN=658e96
export WHITE=d0d0d0

export BOLD_BLACK=5d5d5d
export BOLD_RED=6e4a56
export BOLD_GREEN=486b53
export BOLD_YELLOW=89754e
export BOLD_BLUE=5f7ab1
export BOLD_MAGENTA=807793
export BOLD_CYAN=126a7b
export BOLD_WHITE=f6f6f6

export CURSOR_COLOR=$YELLOW

