#!/usr/bin/zsh
export FOREGROUND=98d1ce
export BACKGROUND=0a0f14

export BLACK=0a0f14
export RED=c33027
export GREEN=26a98b
export YELLOW=edb54b
export BLUE=195465
export MAGENTA=4e5165
export CYAN=33859d
export WHITE=98d1ce

export BOLD_BLACK=10151b
export BOLD_RED=d26939
export BOLD_GREEN=081f2d
export BOLD_YELLOW=245361
export BOLD_BLUE=093748
export BOLD_MAGENTA=888ba5
export BOLD_CYAN=599caa
export BOLD_WHITE=d3ebe9

export CURSOR_COLOR=$YELLOW

# by whatyouhide
