#!/usr/bin/zsh
export FOREGROUND=eceff1
export BACKGROUND=263238

export BLACK=263238
export RED=ff9800
export GREEN=8bc34a
export YELLOW=ffc107
export BLUE=03a9f4
export MAGENTA=e91e63
export CYAN=009688
export WHITE=cfd8dc

export BOLD_BLACK=37474f
export BOLD_RED=ffa74d
export BOLD_GREEN=9ccc65
export BOLD_YELLOW=ffa000
export BOLD_BLUE=81d4fa
export BOLD_MAGENTA=ad1457
export BOLD_CYAN=26a69a
export BOLD_WHITE=eceff1

export CURSOR_COLOR=$YELLOW

