#!/usr/bin/zsh
export FOREGROUND=e8dfd6
export BACKGROUND=021b21

export BLACK=032c36
export RED=c2454e
export GREEN=7cbf9e
export YELLOW=8a7a63
export BLUE=2e3340
export MAGENTA=ff5879
export CYAN=44b5b1
export WHITE=f2f1b9

export BOLD_BLACK=065f73
export BOLD_RED=ef5847
export BOLD_GREEN=a2d9b1
export BOLD_YELLOW=beb090
export BOLD_BLUE=61778d
export BOLD_MAGENTA=ff99a1
export BOLD_CYAN=9ed9d8
export BOLD_WHITE=f6f6c9

export CURSOR_COLOR=$YELLOW

# by hal
