#!/usr/bin/zsh
export FOREGROUND=ffcccf
export BACKGROUND=1c1c1c
export CURSOR_COLOR=f7a600

export BLACK=1c1c1c
export RED=ff0035
export GREEN=8aa600
export YELLOW=f7a600
export BLUE=004f8f
export MAGENTA=ff0068
export CYAN=008988
export WHITE=ffcccf

export BOLD_BLACK=20100d
export BOLD_RED=d6002c
export BOLD_GREEN=809a00
export BOLD_YELLOW=eb920e
export BOLD_BLUE=5a6885
export BOLD_MAGENTA=d63564
export BOLD_CYAN=637d74
export BOLD_WHITE=ffe6e9
