#!/usr/bin/zsh

export FOREGROUND=fae3bb
export BACKGROUND=27231f

export BLACK=27231f
export RED=c8bba0
export GREEN=dbcbaf
export YELLOW=bba883
export BLUE=b08d94
export MAGENTA=8a6e74
export CYAN=855d65
export WHITE=fae3bb

export BOLD_BLACK=201e19
export BOLD_RED=b0935a
export BOLD_GREEN=8a6a31
export BOLD_YELLOW=856324
export BOLD_BLUE=b05264
export BOLD_MAGENTA=8a3243
export BOLD_CYAN=852437
export BOLD_WHITE=fabcc8

export CURSOR_COLOR=$YELLOW

