#!/usr/bin/zsh

export FOREGROUND=c7c8be
export BACKGROUND=231d20

export BLACK=231d20
export RED=c81c61
export GREEN=1ca6c8
export YELLOW=1cc872
export BLUE=c8681c
export MAGENTA=c81ca3
export CYAN=b1c81c
export WHITE=c7c8be

export BOLD_BLACK=1d171a
export BOLD_RED=db0057
export BOLD_GREEN=22c8f1
export BOLD_YELLOW=21e884
export BOLD_BLUE=e57720
export BOLD_MAGENTA=df1fb5
export BOLD_CYAN=d0eb21
export BOLD_WHITE=ecede1

export CURSOR_COLOR=$YELLOW

