#!/usr/bin/zsh
export FOREGROUND=a9b0b8
export BACKGROUND=151515

export BLACK=151515
export RED=b84376
export GREEN=b0b82b
export YELLOW=b89f3f
export BLUE=2b6fb8
export MAGENTA=b840ab
export CYAN=3291b8
export WHITE=a9b0b8

export BOLD_BLACK=2b2b29
export BOLD_RED=b80050
export BOLD_GREEN=adb800
export BOLD_YELLOW=b89200
export BOLD_BLUE=0059b8
export BOLD_MAGENTA=b800a4
export BOLD_CYAN=0082b8
export BOLD_WHITE=d0d9e3

export CURSOR_COLOR=$YELLOW

