#!/usr/bin/zsh
export FOREGROUND=c5c8c6
export BACKGROUND=181512
export BLACK=282a2e
export BOLD_BLACK=373b41
export RED=7b8748
export BOLD_RED=707c3d
export GREEN=b5bd68
export BOLD_GREEN=8c9440
export YELLOW=af865a
export BOLD_YELLOW=a47b4f
export BLUE=7b8753
export BOLD_BLUE=707c48
export MAGENTA=7b6e64
export BOLD_MAGENTA=706359
export CYAN=657c3d
export BOLD_CYAN=5a7032
export WHITE=ccdcbe
export BOLD_WHITE=c1d1b3
export CURSOR_COLOR=$YELLOW

# http://dotshare.it/dots/1058/
