#!/usr/bin/zsh

export FOREGROUND=34302d
export BACKGROUND=f5e7de

export BLACK=666661
export RED=992e2e
export GREEN=4c3226
export YELLOW=a67c53
export BLUE=4c7399
export MAGENTA=bf9986
export CYAN=d97742
export WHITE=34302d

export BOLD_BLACK=7f7f7a
export BOLD_RED=b23636
export BOLD_GREEN=664233
export BOLD_YELLOW=bf8f60
export BOLD_BLUE=5986b2
export BOLD_MAGENTA=d9ae98
export BOLD_CYAN=f2854a
export BOLD_WHITE=4c4742

export CURSOR_COLOR=$YELLOW

