#!/usr/bin/env ruby
# coding: utf-8

def col(key, name)
  return [ key, ENV[name], ENV["BOLD_" + name] ]
end

colors = [
  col(:bla, "BLACK"),
  col(:red, "RED"),
  col(:gre, "GREEN"),
  col(:yel, "YELLOW"),
  col(:blu, "BLUE"),
  col(:mag, "MAGENTA"),
  col(:cya, "CYAN"),
  col(:whi, "WHITE"),
]

def esc(code, value)
  printf("\e%s%s", code, value)
end
  

def apply_colors(colors)
  8.times do |i|
    code = ']P' + i.to_s(16).upcase
    esc(code, colors[i][1])
    code = ']P' + (i+8).to_s(16).upcase
    esc(code, colors[i][2])
  end
end

def reset
  esc('[', '0m')
end

def bold
  esc('[', '1m')
end

def norm
  esc('[', '22m')
end

def color_print(color, *items)
  esc('[', color.to_s + 'm')
  items.each do |item|
    print(item)
    print(" ")
  end
end

def print_ui(colors)
  puts '    NORM BOLD'
  apply_colors(colors)
  8.times do |i|
    k = colors[i]
    n = 30 + i
    norm
    color_print(n, k[0], '████')
    bold
    color_print(n, "████")
    norm
    color_print(n, k[1])
    bold
    color_print(n, k[2])
    puts
  end
  reset
end

print_ui(colors)
