#!/usr/bin/zsh

TOTAL_COMMAND=""
POS=0

while true ; do
    NEXT_COMMAND="$(herbstclient complete $POS ${=TOTAL_COMMAND} | sort | dmenu)"
    if test -z "$NEXT_COMMAND" ; then
        exec herbstclient ${=TOTAL_COMMAND}
    fi

    TOTAL_COMMAND="$TOTAL_COMMAND $NEXT_COMMAND"
    POS=$((POS + 1))
done

