#!/usr/bin/env ruby
# Provides syntax highlighting for irc in the shell

last_nick = nil
STDIN.each_line do |line|
  date, time, nick, msg = line.split(' ', 4)
  if nick != last_nick
    puts
  end
  puts "\x1b[33m#{date} \x1b[34m#{time} \x1b[36m#{nick}\n\x1b[0m#{msg}"
  last_nick = nick
end
