#!/usr/bin/env ruby
# Provides syntax highlighting for irc in the shell

last_nick = nil
last_change = Time.new
max_diff = 90

STDIN.each_line do |line|
  date, time, nick, msg = line.split(' ', 4)
  if msg.strip.empty?
    next
  end
  t = Time.new *date.split('-'), *time.split(':')
  diff = t - last_change
  last_change = t
  if nick != last_nick or diff > max_diff
    puts "\n\x1b[33m#{date} \x1b[34m#{time} \x1b[36m#{nick}" 
  end
  puts "\x1b[0m#{msg}"
  last_nick = nick
end
