#!/usr/bin/env ruby
# Provides syntax highlighting for irc in the shell

STDIN.each_line do |line|
  date, time, nick, msg = line.split(' ', 4)
  puts "\x1b[33m#{date} \x1b[34m#{time} \x1b[35m#{nick} \x1b[0m#{msg}"
end
