#!/usr/bin/zsh
set -e
test -n "$BLACK" \
     -a -n "$RED" \
     -a -n "$GREEN" \
     -a -n "$YELLOW" \
     -a -n "$BLUE" \
     -a -n "$MAGENTA" \
     -a -n "$CYAN" \
     -a -n "$WHITE" \
     -a -n "$BOLD_BLACK" \
     -a -n "$BOLD_RED" \
     -a -n "$BOLD_GREEN" \
     -a -n "$BOLD_YELLOW" \
     -a -n "$BOLD_BLUE" \
     -a -n "$BOLD_MAGENTA" \
     -a -n "$BOLD_CYAN" \
     -a -n "$BOLD_WHITE"
set +e

echo -e "\e]P0$BLACK"
echo -e "\e]P1$RED"
echo -e "\e]P2$GREEN"
echo -e "\e]P3$YELLOW"
echo -e "\e]P4$BLUE"
echo -e "\e]P5$MAGENTA"
echo -e "\e]P6$CYAN"
echo -e "\e]P7$WHITE"
echo -e "\e]P8$BOLD_BLACK"
echo -e "\e]P9$BOLD_RED"
echo -e "\e]PA$BOLD_GREEN"
echo -e "\e]PB$BOLD_YELLOW"
echo -e "\e]PC$BOLD_BLUE"
echo -e "\e]PD$BOLD_MAGENTA"
echo -e "\e]PE$BOLD_CYAN"
echo -e "\e]PF$BOLD_WHITE"
clear
